name: thinformer-torch-2.6
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - expat=2.6.4
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - python=3.12.9
  - readline=8.2
  - sqlite=3.45.3
  - tk=8.6.14
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
    - absl-py==2.1.0
    - aiohappyeyeballs==2.4.6
    - aiohttp==3.11.12
    - aiosignal==1.3.2
    - anyio==4.8.0
    - attrs==25.1.0
    - blosc2==3.1.1
    - certifi==2025.1.31
    - cfgv==3.4.0
    - contourpy==1.3.1
    - cycler==0.12.1
    - distlib==0.3.9
    - einops==0.8.1
    - filelock==3.17.0
    - fonttools==4.56.0
    - frozenlist==1.5.0
    - fsspec==2025.2.0
    - grpcio==1.70.0
    - h11==0.14.0
    - httpcore==1.0.7
    - httpx==0.28.1
    - identify==2.6.7
    - idna==3.10
    - jinja2==3.1.5
    - kiwisolver==1.4.8
    - lightning==2.5.0.post0
    - lightning-bolts==0.7.0
    - lightning-utilities==0.12.0
    - markdown==3.7
    - markupsafe==3.0.2
    - matplotlib==3.10.0
    - mpmath==1.3.0
    - msgpack==1.1.0
    - multidict==6.1.0
    - ndindex==1.9.2
    - networkx==3.4.2
    - nodeenv==1.9.1
    - numexpr==2.10.2
    - numpy==2.2.3
    - nvidia-cublas-cu12==12.4.5.8
    - nvidia-cuda-cupti-cu12==12.4.127
    - nvidia-cuda-nvrtc-cu12==12.4.127
    - nvidia-cuda-runtime-cu12==12.4.127
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.2.1.3
    - nvidia-curand-cu12==10.3.5.147
    - nvidia-cusolver-cu12==11.6.1.9
    - nvidia-cusparse-cu12==12.3.1.170
    - nvidia-cusparselt-cu12==0.6.2
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.4.127
    - packaging==24.2
    - pandas==2.2.3
    - pillow==11.1.0
    - pip==25.0
    - platformdirs==4.3.6
    - pre-commit==4.1.0
    - propcache==0.2.1
    - protobuf==5.29.3
    - py-cpuinfo==9.0.0
    - pyparsing==3.2.1
    - python-dateutil==2.9.0.post0
    - pytorch-fast-transformers==0.4.0
    - pytorch-lightning==1.9.5
    - pytz==2025.1
    - pyyaml==6.0.2
    - setuptools==75.8.0
    - six==1.17.0
    - sniffio==1.3.1
    - sympy==1.13.1
    - tables==3.10.2
    - tabulate==0.9.0
    - tensorboard==2.19.0
    - tensorboard-data-server==0.7.2
    - thinformer==0.0.0
    - timm==0.3.4
    - torch==2.6.0
    - torchaudio==2.6.0
    - torchmetrics==1.6.1
    - torchvision==0.21.0
    - tqdm==4.67.1
    - triton==3.2.0
    - typing-extensions==4.12.2
    - tzdata==2025.1
    - virtualenv==20.29.2
    - werkzeug==3.1.3
    - wheel==0.45.1
    - yarl==1.18.3
